lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
#    plug NavigationHistory.Tracker
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/posts", PostController
    resources "/users", UserController
    resources "/follows", FollowController
    resources "/hashtags", HashtagController
    resources "/tagposts", TagpostController
    post "/sessions", SessionController,  :login
    delete "/sessions", SessionController, :logout
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", MicroblogWeb do
    pipe_through :api
    
    resources "/likes", LikeController, except: [:new, :edit]
  end
end

lib/microblog/blog/post.ex
defmodule Microblog.Blog.Post do
  use Ecto.Schema
  import Ecto.Changeset
  alias Microblog.Blog.Post


  schema "posts" do
    field :content, :string
    field :title, :string
    belongs_to :user, Microblog.Accounts.User

    timestamps()
  end

  @doc false
  def changeset(%Post{} = post, attrs) do
    post
    |> cast(attrs, [:title, :content, :user_id])
    |> validate_required([:title, :content, :user_id])
  end
end

lib/microblog_web/controllers/post_controller.ex
defmodule MicroblogWeb.PostController do
  use MicroblogWeb, :controller

  alias Microblog.Blog
  alias Microblog.Blog.Post

  def index(conn, _params) do
    posts = Blog.list_posts()
    current_user = conn.assigns[:current_user]
    if current_user do 
      users = Enum.map(posts, fn(s) -> s.user_id end)
      render(conn, "index.html", posts: posts, users: users)
    else
      conn 
      |> redirect(to: "/users/new")
      |> halt()

    end
  end

  def new(conn, _params) do
    current_user = conn.assigns[:current_user]
    if current_user do 
      changeset = Blog.change_post(%Post{})
      render(conn, "new.html", changeset: changeset)
    else
      conn 
      |> redirect(to: "/users/new")
      |> halt()

    end
  end

  def create(conn, %{"post" => post_params}) do
    case Blog.create_post(post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post created successfully.")
        |> redirect(to: Enum.join([post_path(conn, :show, post),"#newPost"], ""))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    post = Blog.get_post!(id)
    user = Microblog.Accounts.get_user!(post.user_id)
    current_user = conn.assigns[:current_user]

    if current_user do
      user_liked = Microblog.Accounts.user_liked_post?(current_user.id, post.id)
      user_liked_post = user_liked
      render(conn, "show.html", post: post, user: user, user_liked_post: user_liked_post)
    else
      conn 
      |> redirect(to: "/users/new")
      |> halt()
    end 
  end

  def edit(conn, %{"id" => id}) do
    post = Blog.get_post!(id)
    current_user = conn.assigns[:current_user]
    if current_user do 
      changeset = Blog.change_post(post)
      render(conn, "edit.html", post: post, changeset: changeset)
    else
      conn 
      |> redirect(to: "/users/new")
      |> halt()

    end
  end

  def update(conn, %{"id" => id, "post" => post_params}) do
    post = Blog.get_post!(id)

    case Blog.update_post(post, post_params) do
      {:ok, post} ->
        conn
        |> put_flash(:info, "Post updated successfully.")
        |> redirect(to: post_path(conn, :show, post))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", post: post, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    post = Blog.get_post!(id)
    {:ok, _post} = Blog.delete_post(post)

    conn
    |> put_flash(:info, "Post deleted successfully.")
    |> redirect(to: post_path(conn, :index))
  end
end

lib/microblog_web/views/post_view.ex
defmodule MicroblogWeb.PostView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/post/edit.html.eex
<h2>Edit Post</h2>

<%= render "form.html", Map.put(assigns, :action, post_path(@conn, :update, @post)) %>

<span><%= link "Back", to: post_path(@conn, :index) %></span>

lib/microblog_web/templates/post/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>
<div id="messages" class="container"></div>
  <div class="form-group">
    <%= label f, :title, class: "control-label" %>
    <%= text_input f, :title, class: "form-control" %>
    <%= error_tag f, :title %>
  </div>

  <div class="form-group">
    <%= label f, :content, class: "control-label" %>
    <%= textarea f, :content, rows: 12, class: "form-control" %>
    <%= error_tag f, :content %>
  </div>


  <div class="form-group">
    <%= hidden_input f, :user_id, class: "form-control", value: @current_user.id %>
    <%= error_tag f, :user_id %>
  </div>

  <div id="post-publish" class="form-group">
    <%= submit "Publish", class: "btn btn-success" %>
  </div>
<% end %>

lib/microblog_web/templates/post/index.html.eex
<!-- Blog entries -->
<div class="container">  
  <%= if @current_user do %>

  <span><%= link "New Post", to: post_path(@conn, :new), class: "btn btn-primary" %></span>



  <h2 class="my-4">Posts Feed</h2>
  <%= for post <- Enum.reverse(@posts) do %>
    <div id="post-entries" >
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <!-- Blog post -->
        <div class="card">
          <div class="card-block">

            <div class="well well-lg">
              <div class="card-body">
                <h3 class="card-title"><%= post.title %></h3>
              </br>
              <p class="card-text">
                <%= post.content %>
                <span><%= link "Read more...", to: post_path(@conn, :show, post), class: "card-link" %></span>
              </p>
            </div>

            <div class="card-footer text-muted">
             <p> Posted on <%= post.inserted_at %> by <%= post.user.display_name %> </p>
             <div id="like-bar">
              <div id="post-likes"
              data-path="<%= like_path(@conn, :index) %>"
              data-post_id="<%= post.id %>">
            </div>

            <script id="likes-template" type="text/x-handlebars-template">
              <div class="m-2">
                <p> Liked by:

                  {{#each data}}
                  {{user_name}}, 

                  {{else}}
                  no one yet.
                {{/each}} </p>                                             

              </div>
            </script>
          </div>
        </div>
      </div>
    </div>

  </div>
</br>
</div>

</div>
</div>

</div>
</ br>
<% end %>
<% end %>
</div>

lib/microblog_web/templates/post/new.html.eex
<h2>New Post</h2>

<%= render "form.html", Map.put(assigns, :action, post_path(@conn, :create)) %>

<span><%= link "Back", to: post_path(@conn, :index) %></span>

lib/microblog_web/templates/post/show.html.eex
<%= if @current_user do %>
<script type="text/javascript">
  window.current_Id = <%= @current_user.id %>;
  window.post_id = <%= @post.id %>;
  window.post_title = "<%= @post.title %>";
  window.post_content = "<%= @post.content %>";
  window.post_user = <%= @post.user_id %>;
</script>
<% end %>

<ol class="breadcrumb">
  <li class="breadcrumb-item"><%= link("Posts", to: post_path(@conn, :index)) %></li>
  <li class="breadcrumb-item active"><%= @post.title %></li>
</ol>
<h2><%= @post.title %></h2>

<div class="container" >
 

  <div id="post-info">
    <p>Posted by <%= @post.user.name %> at <%= @post.inserted_at %>
    </p>
  </div>

  <div id="show-content">
    <p class="span6" rows="12">
    <%= @post.content %>
    </tp>
 
  <div id="like-bar">

     <div id="post-likes"
          data-path="<%= like_path(@conn, :index) %>"
          data-post_id="<%= @post.id %>">
        &nbsp;
     </div>
   
    <script id="likes-template" type="text/x-handlebars-template">
      <div class="m-2">
        <p> Liked by:

        {{#each data}}
          {{user_name}}, 

	{{else}}
	  no one yet.
        {{/each}} </p>                                             

      </div>
    </script>

    <%= if @current_user do %>
      <%= if @user_liked_post do %>
        <button id="like-button" class="btn btn-info" data-user_id="<%= @current_user.id %>" >Like</button>
        
      <% end %>
    <% end %>
  </div>

  </div>
</br>
</div>

<div class="container" >
<span><%= link "Back", to: post_path(@conn, :index), class: "btn btn-primary" %></span>

<%= if (@current_user && @post.user_id==@current_user.id )|| (@current_user.admin_status) do %>
  <span>
    <%= link "Edit", to: post_path(@conn, :edit, @post), class: "btn btn-warning" %>
  </span>
  <span>
    <%= link "Delete Post", to: post_path(@conn, :delete,  @post), method: :delete, data: [confirm: "Are you sure you want to delete this post?"],  class: "btn btn-danger" %>
  </span>
<% end %>

</div>