lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
#    plug NavigationHistory.Tracker
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/posts", PostController
    resources "/users", UserController
    resources "/follows", FollowController
    resources "/hashtags", HashtagController
    resources "/tagposts", TagpostController
    post "/sessions", SessionController,  :login
    delete "/sessions", SessionController, :logout
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", MicroblogWeb do
    pipe_through :api
    
    resources "/likes", LikeController, except: [:new, :edit]
  end
end

lib/microblog/accounts/user.ex
defmodule Microblog.Accounts.User do
  use Ecto.Schema
  import Ecto.Changeset
  alias Microblog.Accounts.User

# Attribution: Prof. Nat Tucks' lecture notes on passwords & comeonin doc
  schema "users" do
    field :display_name, :string
    field :email, :string
    field :name, :string

    field :admin_status, :boolean

    field :password_hash, :string
    field :pw_tries, :integer
    field :pw_last_try, :utc_datetime

    field :password, :string, virtual: true
    field :password_confirmation, :string, virtual: true

    timestamps()
  end

  @doc false
  def changeset(%User{} = user, attrs) do
    user
    |> cast(attrs, [:name, :display_name, :email, :password, :password_confirmation, :admin_status])
    |> validate_confirmation(:password)
    |> validate_password(:password)
    |> put_pass_hash()
    |> validate_required([:name, :display_name, :email, :password_hash])
  end

  # Password validation
  def validate_password(changeset, field, options \\ []) do
    validate_change(changeset, field, fn _, password ->
      case valid_password?(password) do
        {:ok, _} -> []
        {:error, msg} -> [{field, options[:message] || msg}]
      end
    end)
  end

  def put_pass_hash(%Ecto.Changeset{valid?: true, changes: %{password: password}} = changeset) do
    change(changeset, Comeonin.Argon2.add_hash(password))
  end

  def put_pass_hash(changeset), do: changeset

  def valid_password?(password) when byte_size(password) > 7 do
    {:ok, password}
  end

  def valid_password?(_), do: {:error, "The password is too short"}
  
end

lib/microblog_web/controllers/user_controller.ex
defmodule MicroblogWeb.UserController do
  use MicroblogWeb, :controller

  alias Microblog.Accounts
  alias Microblog.Accounts.User
  alias Microblog.Accounts.Follow

  def index(conn, _params) do
    users = Accounts.list_users()
    current_user = conn.assigns[:current_user]
    if current_user do 
      render(conn, "index.html", users: users)
    else
      conn 
      |> redirect(to: "/")
      |> halt()

    end
  end

  def new(conn, _params) do
    current_user = conn.assigns[:current_user]
    if !current_user do 
      changeset = Accounts.change_user(%User{})
      render(conn, "new.html", changeset: changeset)
    else
      conn 
      |> redirect(to: "/posts")
      |> halt()

    end
  end

  def create(conn, %{"user" => user_params}) do
    case Accounts.create_user(user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User created successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    current_user = conn.assigns[:current_user]

    if current_user do
      post = Microblog.Blog.change_post(%Microblog.Blog.Post{user_id: user.id})
      follow = Accounts.change_follow(%Microblog.Accounts.Follow{follower_user_id: current_user.id, following_user_id: user.id})
      render(conn, "show.html", current_user: current_user, user: user, post: post, follow: follow)
    else
      conn
      |> redirect(to: "/")
      |> halt()
    end
  end

  def edit(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    current_user = conn.assigns[:current_user]
    if current_user do 
      if current_user.admin_status || current_user.id == user.id do
        changeset = Accounts.change_user(user)
        render(conn, "edit.html", user: user, changeset: changeset)
      else
        conn
        |> redirect(to: "/posts")
        |> halt()
      end

    else
      conn 
      |> redirect(to: "/users/new")
      |> halt()

    end
  end

  def update(conn, %{"id" => id, "user" => user_params}) do
    user = Accounts.get_user!(id)

    case Accounts.update_user(user, user_params) do
      {:ok, user} ->
        conn
        |> put_flash(:info, "User updated successfully.")
        |> redirect(to: user_path(conn, :show, user))
      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", user: user, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    user = Accounts.get_user!(id)
    {:ok, _user} = Accounts.delete_user(user)

    conn
    |> put_flash(:info, "User deleted successfully.")
    |> redirect(to: user_path(conn, :index))
  end
end

lib/microblog_web/views/user_view.ex
defmodule MicroblogWeb.UserView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/user/edit.html.eex
<h2>Edit User</h2>

<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :update, @user)) %>

<span><%= link "Back", to: user_path(@conn, :index) %></span>

lib/microblog_web/templates/user/form.html.eex
<%= form_for @changeset, @action, fn f -> %>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <div class="form-group">
    <%= label f, :name, class: "control-label" %>
    <%= text_input f, :name, class: "form-control" %>
    <%= error_tag f, :name %>
  </div>

  <div class="form-group">
    <%= label f, :display_name, class: "control-label" %>
    <%= text_input f, :display_name, class: "form-control" %>
    <%= error_tag f, :display_name %>
  </div>

  <div class="form-group">
    <%= label f, :email, class: "control-label" %>
    <%= text_input f, :email, class: "form-control" %>
    <%= error_tag f, :email %>
  </div>

  <div class="form-group">
    <%= label f, :password, class: "control-label" %>
    <%= password_input f, :password, class: "form-control" %>
    <%= error_tag f, :password %>
  </div>

  <div class="form-group">
    <%= label f, :password_confirmation, class: "control-label"%>
    <%= password_input f, :password_confirmation, class: "form-control" %>
    <%= error_tag f, :password_confirmation %>
  </div>

  <div class="form-group">
    <%= submit "Submit", class: "btn btn-primary" %>
  </div>
<% end %>

lib/microblog_web/templates/user/index.html.eex
<h2>Listing Users</h2>

<div class="col-lg-8 col-sm-6">
  <%= for (user <- @users) do %>
  <%= if @current_user != user do %>
  <div class="well-lg">
    <div class="card hovercard">

     <div class="card-body">
       <h4 class="card-title"> <%= user.name %>'s Bio: </h4>
       <p class="card-text">
         Pen name: <%= user.display_name %>
       </br>
       Email: <%= user.email %>
     </p>

   </div>


   <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">

    <div class="btn-group" role="group">
      <span><%= link "Go to Profile", to: user_path(@conn, :show, user), class: "btn btn-primary" %>
      </span>
    </div>

  </div>


</div>
</br>
<% end %>
<% end %>

</div>

<span><%= link "New User", to: user_path(@conn, :new) %></span>

lib/microblog_web/templates/user/new.html.eex
<div class="container">

<h1 align="center"> Welcome to Microblog!</h1>
</br>
<h3>Register a New Account</h3>

</div>
<%= render "form.html", Map.put(assigns, :action, user_path(@conn, :create)) %>

lib/microblog_web/templates/user/show.html.eex
<h2>Welcome to <%= @user.display_name %>'s Profile!</h2>

<div class="col-lg-8 col-sm-6">
 <div class="well-lg">
  <div class="card hovercard">

	<div class="card-body">
    	  <h4 class="card-title"> <%= @user.name %>'s Bio: </h4>
	
	  <p class="card-text">
	    Pen name: <%= @user.display_name %>
            </br>
            Email: <%= @user.email %>
	  </p>

       </div>
     

    <div class="btn-pref btn-group btn-group-justified btn-group-lg" role="group" aria-label="...">

      <div class="btn-group" role="group">
        <span><%= link "Posts", to: post_path(@conn, :index), class: "btn btn-primary" %>
        </span>
      </div>

      <div class="btn-group" role="group">
        <span><%= link "Followers", to: user_path(@conn, :index), class: "btn btn-primary" %>
        </span>
      </div>

      <div class="btn-group" role="group">
        <span><%= link "Following", to: user_path(@conn, :index), class: "btn btn-primary" %>
        </span>
      </div>
   </div>

      <%= if @current_user && @current_user != @user do %>
	<%= form_for @follow, follow_path(@conn, :create), fn f -> %>
  	  <%= if @follow.action do %>
    	  <div class="alert alert-danger">
      	  <p>Oops, something went wrong! Please check the errors below.</p>
    	  </div>
  	  <% end %>

  	  <%= hidden_input f, :follower_user_id %>
	  <%= hidden_input f, :following_user_id %>

 	   <div class="form-group">
   	   <%= submit "Follow Me!", class: "btn btn-success" %>
  	  </div>
	<% end %>

      <% end %>
  </div>

 </div>

<span><%= link "Back", to: user_path(@conn, :index), class: "btn btn-primary" %></span>

<%= if @current_user && (@current_user.admin_status || @current_user.id == @user.id)do %>
  <span>
    <%= link "Edit", to: user_path(@conn, :edit, @user), class: "btn btn-warning" %>
  </span>
  <span>
    <%= link "Delete User", to: user_path(@conn, :delete,  @user), method: :delete, data: [confirm: "Are you sure you want to delete this user?"],  class: "btn btn-danger" %>
  </span>
<% end %>

</div>