lib/microblog_web/router.ex
defmodule MicroblogWeb.Router do
  use MicroblogWeb, :router
  import MicroblogWeb.Plugs

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
#    plug NavigationHistory.Tracker
    plug :fetch_user
  end

  pipeline :api do
    plug :accepts, ["json"]
    plug :fetch_session
    plug :fetch_user
  end

  scope "/", MicroblogWeb do
    pipe_through :browser # Use the default browser stack

    get "/", PageController, :index
    resources "/posts", PostController
    resources "/users", UserController
    resources "/follows", FollowController
    resources "/hashtags", HashtagController
    resources "/tagposts", TagpostController
    post "/sessions", SessionController,  :login
    delete "/sessions", SessionController, :logout
  end

  # Other scopes may use custom stacks.
  scope "/api/v1", MicroblogWeb do
    pipe_through :api
    
    resources "/likes", LikeController, except: [:new, :edit]
  end
end

lib/microblog_web/views/layout_view.ex
defmodule MicroblogWeb.LayoutView do
  use MicroblogWeb, :view
end

lib/microblog_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Hello Microblog!</title>
  <link rel="stylesheet" href="<%= static_path(@conn, "/css/app.css") %>">
</head>


<body>

 <!-- Attribution: Nav bar from lecture code-->
 <nav class="navbar navbar-custom navbar-expand-md">
  <%= if @current_user do %>
  <a class="navbar-brand" href="/posts">Microblog</a>
  <% else %>

  <a class="navbar-brand" href="/users/new">Microblog</a>
  <% end %>
  <button class="navbar-toggler" type="button"
  data-toggle="collapse" data-target="#main-navbar">
  <span class="navbar-toggler-icon"></span>
  </button>

<%= if @current_user do %>
<div class="collapse navbar-collapse" id="main-navbar">
  <ul class="navbar-nav mr-auto">
    <li class="nav-item">
     <%= link "Posts", to: post_path(@conn, :index), class: "nav-link" %>
   </li>
   <li class="nav-item">
     <%= link "Users", to: user_path(@conn, :index), class: "nav-link" %>
   </li>
 </ul>
</div>


<span class="text-light">
  <strong><%= @current_user.name %></strong> |
  <%= link("logout", to: session_path(@conn, :logout), method: :delete) %>
</span>
<li class="nav-item">
 <%= link "My Profile", to: user_path(@conn, :show, @current_user), class: "nav-link"%> </li>

 <% else %>
 <%= form_for @conn, session_path(@conn, :login), 
 [as: "user", class: "form-inline w-75"], fn _f -> %>
 <input type="text" placeholder="email" class="form-control" name="email">
 <input type="password" placeholder="password" class="form-control" name="password">
 <input type="submit" value="Log in" class="btn btn-primary">
 <% end %>
 <% end %>

</nav>

<div class="container">

  <div class="row">
    <div class="col-sm-12 my-2">
      <%= if get_flash(@conn, :info) do %> 
      <p class="alert alert-info" role="alert"><%= get_flash(@conn, :info) %></p>
      <% end %>
      <%= if get_flash(@conn, :error) do %> 
      <p class="alert alert-danger" role="alert"><%= get_flash(@conn, :error) %></p>
      <% end %>
    </div>
  </div>

  <div class="row">
    <div class="col-sm-8">
      <%= render @view_module, @view_template, assigns %>
    </div>
  </div>

</div> <!-- container -->

<script src="<%= static_path(@conn, "/js/app.js") %>"></script>
</body>
</html>